# 에러 & 예외 처리

* 에러(Error)
* 예외처리(Exception Handling)

--------

![0727_1](../python_asset/0727_1.png)

> #  에러 (Error)
>
> > ### 1.1 문법 에러(Suntax Error)
> >
> > * 문법 에러가 있는 프로그램은 실행되지 않는다.
> >
> >   - 에러 발생 시 `SyntaxError`라는 키워드와 함께, 에러의 상세 내용을 보여준다.
> >
> >   - `파일이름`과 `줄번호`, `^` 문자를 통해 파이썬이 코드를 읽어 들일 때(`parser`) 문제가 발생한 위치를 표현한다.
> >
> >   - `parser` 는 줄에서 에러가 감지된 가장 앞의 위치를 가리키는 캐럿(caret)기호(`^`)를 표시한다.
> >
> > ```python
> > SyntaxError: invalid syntax # 문법 오류
> > SyntaxError: EOL while scanning string literal # 따옴표 오류
> > SyntaxError: unexpected EOF while parsing # 괄호 닫기 오류
> > 
> > ```
> >
> > ### 1.2 예외(Exception)
> >
> > * 실행 도중 예상하지 못한 상황(exception)을 맞이하면, 프로그램 실행을 멈춥니다.
> >
> > - 문법적으로는 옳지만, 실행시 발생하는 에러입니다.
> >
> > - *아래 제시된 모든 에러는 `Exception`을 상속받아 이뤄진다.*
> >
> > ```python
> > ZeroDivisionError # 상수를 0으로 나눌 때
> > NameError: name 'abc' is not defined # 정의되지 않은 값 사용
> > unsupported operand type(s) for +: 'int' and 'str' # 타입간 올바르지 않은 연산자 사용
> > type str doesn't define __round__ method # 해당 메서드가 타입에 없을 때 발생 
> > sample() missing 1 required positional argument: 'k' # 매개 변수 누락 
> > choice() takes 2 positional arguments but 3 were given # 매개 변수 갯수 안 맞음
> > invalid literal for int() with base 10: '3.5' # 자료형은 올바르나 값이 맞지 않음
> > ValueError: 3 is not in list # 찾고자 하는 값이 없을 때 발생
> > IndexError: list index out of range # 주소 값을 넘어갈 때 발생
> > KeyError: 'queen' # Dictionary에 해당 key가 없을 때
> > ModuleNotFoundError: No module named 'reque'#존재하지 않는 모듈 접근
> > ImportError # 모듈은 찾았으나 존재하지 않는 클래스, 함수 호출
> > KeyboardInterrupt # ctrl-c 등 키 입력을 통한 방해로 중지
> > 
> > ```
>
> 
>
> ## 예외 처리(Exception Handling)
>
> > ### 2.1 try & except
> >
> > * `try`문을 이용하여 예외 처리를 할 수 있다.
> >
> > ```python
> > try:
> >     <코드 블럭 1>
> > except (예외):
> >     <코드 블럭 2>
> > ```
> >
> > - `try` 아래의 코드블락(code block)이 실행된다.
> >
> > - 예외가 발생되지 않으면, **`except`없이 실행이 종료 된다.**
> >
> > - 예외가 발생하면, **남은 부분을 수행하지 않고**, `except`가 실행된다.
> >
> > - **복수의 예외 처리**
> >
> >   * 하나 이상의 예외를 모두 처리할 수 있다.
> >   * 괄호가 있는 튜플로 여러 개의 예외를 지정할 수 있다.
> >
> >   ```python
> >   try:
> >       <코드 블럭 1>
> >   except (예외1, 예외2):
> >       <코드 블럭 2>
> >   
> >   
> >   try:
> >       <코드 블럭 1>
> >   except 예외1:
> >       <코드 블럭 2>
> >   except 예외2:
> >       <코드 블럭 3>
> >   ```
> >
> > - **else**
> >
> >   * 에러가 발생하지 않는 경우 수행되는 문장은 `else`를 이용한다.
> >   * 모든 except 절 뒤에와야 한다.
> >   * try 절이 예외를 일으키지 않을 때 실행되어야만 하는 코드에 적절하다.
> >
> >   ```python
> >   try:
> >       <코드 블럭 1>
> >   except 예외:
> >       <코드 블럭 2>
> >   else:
> >       <코드 블럭 3>
> >   ```
> >
> > - **finally**
> >
> >   * 반드시 수행해야하는 문장은 `finally`를 활용한다.
> >   * 즉, 모든 상황에 실행되어야만 하는 코드를 정의하는데 활용한다.
> >   * 예외의 발생 여부과 관계없이 try 문을 떠날 때 항상 실행한다.
> >
> >   ```python
> >   try:
> >       <코드 블럭 1>
> >   except 예외:
> >       <코드 블럭 2>
> >   finally:
> >       <코드 블럭 3>
> >   ```
> >
> > - **에러 메시지 처리 `as`**
> >
> >   * `as` 키워드를 활용하여 에러 메시지를 보여줄 수도 있다.
> >
> >   ```python
> >   try:
> >       <코드 블럭 1>
> >   except 예외 as err:
> >       <코드 블럭 2>
> >   ```
> >
> > - **예외 발생 시키기(Exception Raising)**
> >
> >   * `raise`
> >     * `raise`를 통해 예외를 강제로 발생시킬 수 있다.
> >
> >   ```python
> >   raise <에러>('메시지')
> >   ```
> >
> >   * `assert`
> >     * `assert` 문은 예외를 발생시키는 다른 방법이다.
> >     * 보통 **상태를 검증하는데 사용**되며 무조건 `AssertionError`가 발생한다.
> >
> >   ```python
> >   assert Boolean expression, error message
> >     
> >   assert len([1, 2]) == 1, '길이가 1이 아닙니다.'
> >   # 위의 검증식이 거짓일 경우를 발생. 
> >   # 일반적으로 디버깅용도로 사용.
> >   ```
> >
> > 

---

### Reference

https://wikidocs.net/66

